/* Generated by MyraPad at 14.12.2019 14:54:23 */
using Myra.Graphics2D.UI;
using System;

namespace Myra.Samples.DebugConsole
{
	public partial class DebugPanel : Panel
	{
		public event EventHandler Removed;

		private void _buttonHideDebug_Click(object sender, MyraEventArgs e)
		{
			RemoveFromDesktop();

			var ev = Removed;
			if (ev != null)
			{
				ev(this, EventArgs.Empty);
			}
		}
	}
}