/* Generated by MyraPad at 14.12.2019 14:54:23 */
using Myra.Graphics2D.UI;
using System;

namespace Myra.Samples.DebugConsole
{
	public partial class DebugPanel : VerticalStackPanel
	{
		public event EventHandler Removed;

        public void ButtonHideDebug_Click(object sender, MyraEventArgs e)
		{
			RemoveFromDesktop();
			 
			if (Removed != null)
			{
                Removed(this, EventArgs.Empty);
			}
		}
	}
}