/* Generated by MyraPad at 14.12.2019 14:46:23 */
using Microsoft.Xna.Framework;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI;

namespace Myra.Samples.DebugConsole
{
	public partial class GamePanel : Panel
	{
		public bool ButtonsEnabled { get; set; } = true;

		private void ShowDebugPanel(bool isModal)
		{
			var debugPanel = new DebugPanel
			{
				Opacity = 0.75f,
				Background = new SolidBrush(Color.Blue),
				IsModal = isModal
			};

			ButtonsEnabled = false;
			 
            debugPanel.Removed += (s, a) =>
			{
				ButtonsEnabled = true;
            };

			Desktop.Widgets.Add(debugPanel);
		}

        public void ButtonDebugPanel_Click(object sender, MyraEventArgs e)
		{
			ShowDebugPanel(false);
		}

		public void ButtonModalDebugPanel_Click(object sender, MyraEventArgs e)
		{
			ShowDebugPanel(true);
		}
	}
}