<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <BuildOutputTargetFolder>tools</BuildOutputTargetFolder>
    <CopyLocalLockFileAssemblies Condition="$(TargetFramework) == 'netstandard2.0'">true</CopyLocalLockFileAssemblies>
    <DebugType>embedded</DebugType>
    <DefineConstants>$(DefineConstants);BUILDTASK;XAMLX_CECIL_INTERNAL;XAMLX_INTERNAL</DefineConstants>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <IncludeSymbols>false</IncludeSymbols>
    <LangVersion>14.0</LangVersion>
    <NoWarn Condition="'$(TargetFramework)' == 'netstandard2.0'">$(NoWarn);nullable</NoWarn>
    <Nullable>enable</Nullable>
    <RootNamespace>Myra.Xaml</RootNamespace>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <TargetFramework>netstandard2.0</TargetFramework>
    <XamlXSourcePath>../../external/XamlX/src/XamlX</XamlXSourcePath>
    <XamlXCecilSourcePath>../../external/XamlX/src/XamlX.IL.Cecil</XamlXCecilSourcePath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(XamlXSourcePath)/**/*.cs" Exclude="$(XamlXSourcePath)/obj/**/*.cs;$(XamlXSourcePath)/Compatibility/*.cs;$(XamlXSourcePath)/**/SreTypeSystem.cs" LinkBase="XamlIl" />
    <Compile Include="$(XamlXCecilSourcePath)/**/*.cs" Exclude="$(XamlXCecilSourcePath)/obj/**/*.cs" LinkBase="XamlIl.Cecil" />
    <PackageReference Include="Microsoft.Build.Framework" Version="18.8.2" PrivateAssets="All" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
  </ItemGroup>

</Project>