<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup> 
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>Myra.Xaml</AssemblyName>
    <BuildOutputTargetFolder>tools</BuildOutputTargetFolder>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <DebugType>embedded</DebugType>
    <DefineConstants>$(DefineConstants);BUILDTASK;</DefineConstants>
    <EnableNETAnalyzers>false</EnableNETAnalyzers>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <IncludeSymbols>false</IncludeSymbols>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>Myra.Xaml</RootNamespace>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <TargetFramework>netstandard2.0</TargetFramework>
    <XamlXSourcePath>../../external/XamlX/src/XamlX</XamlXSourcePath>
    <XamlXCecilSourcePath>../../external/XamlX/src/XamlX.IL.Cecil</XamlXCecilSourcePath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(XamlXSourcePath)/**/*.cs" Exclude="$(XamlXSourcePath)/obj/**/*.cs;$(XamlXSourcePath)/Compatibility/*.cs;$(XamlXSourcePath)/**/SreTypeSystem.cs" LinkBase="XamlIl" />
    <Compile Include="$(XamlXCecilSourcePath)/**/*.cs" Exclude="$(XamlXCecilSourcePath)/obj/**/*.cs" LinkBase="XamlIl.Cecil" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />  
    <PackageReference Include="Microsoft.Build.Framework" Version="18.9.6" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="18.9.6" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Myra\Myra.MonoGame.csproj" />
  </ItemGroup>

</Project>