using Microsoft.Build.Framework; 
using Mono.Cecil;
using Mono.Cecil.Cil;
using Mono.Cecil.Rocks;
using Mono.Collections.Generic;
using Myra.Xaml.Compiler;
using Myra.Xaml.Helpers; 
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq; 
using XamlX.TypeSystem;

namespace Myra.Xaml
{ 
    /// <summary>
    /// Compiles .xaml files to IL and writes that to the target assembly.
    /// </summary>
    public sealed class MyraXamlCompileTask : Microsoft.Build.Utilities.Task
    { 

        [Required]
        public string TargetPath { get; set; } = default!;

        [Required]
        public ITaskItem[] MyraFiles { get; set; } = [];

        [Required]
        public string RootNamespace { get; set; } = null!;

        [Required]
        public string ProjectDirectory { get; set; } = null!;

        [Required]
        public ITaskItem[] ReferenceAssemblies { get; set; } = [];

        public bool Debug { get; set; }

        public CecilTypeSystem? TypeSystem { get; set; }

        private List<(string, IXamlMethod)> _atlasTypes = [];
        private List<(string, IXamlMethod)> _stylesheetTypes = [];

        public override bool Execute()
        {
            Debugger.Launch();
            AssemblyDefinition? assembly = null;
            try
            {
                if (!File.Exists(TargetPath))
                {
                    Log.LogError("Myra XAML: target assembly '{0}' does not exist.", TargetPath);

                    return false;
                }

                if (MyraFiles.Length == 0)
                {
                    Log.LogMessage(MessageImportance.Low, "Myra XAML: no Myra files found.");

                    return true;
                }

                Log.LogMessage(MessageImportance.Normal, "Myra XAML: weaving '{0}'.", TargetPath);
                var assemblies = ReferenceAssemblies
                    .Select(x => x.ItemSpec)
                    .Where(File.Exists)
                    .Distinct(StringComparer.OrdinalIgnoreCase)
                    .ToList();
                TypeSystem = new CecilTypeSystem(assemblies, TargetPath);
                TypesContainer.Setup(TypeSystem);

                var componentsCompiler = new MyraComponentsCompiler(TypeSystem);

                assembly = componentsCompiler.TypeSystem.GetAssembly(componentsCompiler.TypeSystem.FindAssembly(Path.GetFileNameWithoutExtension(TargetPath)!)!);

                // write resource builder before we use it in the XAML handling.
                var resourceType = new TypeDefinition("Myra.AutoGenerated", "__MyraXamlResources",
                                                        TypeAttributes.Class | TypeAttributes.Sealed,
                                                        assembly.MainModule.TypeSystem.Object);
                assembly.MainModule.Types.Add(resourceType);

                var writerParameters = new WriterParameters
                {
                    WriteSymbols = Debug,
                    SymbolWriterProvider = new PortablePdbWriterProvider()
                };
 
                assembly.Write(TargetPath, writerParameters);

                var resourcesBuilder = new MyraResourcesBuilder(TypeSystem, resourceType, componentsCompiler.Configuration.WellKnownTypes);
                assembly.Write(TargetPath, writerParameters);
                var getMethod = resourceType.GetMethods().First(m => m.Name == MyraResourcesBuilder.GetStylesheetMethodName);
                MyraBindingCompilationContext.GetStylesheetDefinition = getMethod.Module.ImportReference(getMethod);

                var stylesheetsCompiler = new MyraStylesheetsCompiler(TypeSystem);


                // group all Myra (xaml, xmat, xmms) files by extension
                // we do the xmat (texture regions) first, given stylesheets (xmms) use them,
                // which in turn are used by XAML files.
                var myraFilesGroupedByExtension = MyraFiles
                    .GroupBy(m => Path.GetExtension(m.ItemSpec))
                    .ToDictionary(m => m.Key, m => m.ToArray());
                 
                if (myraFilesGroupedByExtension.TryGetValue(".xmms", out var stylesheetFiles)) {
                    foreach (var item in stylesheetFiles)
                    {
                        _stylesheetTypes.Add(stylesheetsCompiler.CompileStylesheetFile(assembly, item));
                    }
                }

                if (myraFilesGroupedByExtension.TryGetValue(".xaml", out var xamlFiles))
                {
                    foreach (var item in myraFilesGroupedByExtension[".xaml"])
                    {
                        componentsCompiler.CompileXamlFile(Log, TargetPath, ProjectDirectory, assembly, item);
                    }
                }

                // set up internal MyraResourcesClass for lookups. (for now, only stylesheets)  
                resourcesBuilder.BuildStaticConstructor(_atlasTypes, _stylesheetTypes);
                 
                assembly.Write(TargetPath, writerParameters);

                Log.LogMessage(MessageImportance.Normal, "Myra XAML: finished weaving '{0}'.", TargetPath);

                return !Log.HasLoggedErrors;
            }
            catch (Exception ex)
            {
                Log.LogErrorFromException(ex, showStackTrace: true);
                return false;
            }
            finally
            {
                assembly?.Dispose();
            }
        }

        
        

        private static TypeDefinition? FindTypeRecursive(Collection<TypeDefinition> types, string fullName)
        {
            foreach (var type in types)
            {
                if (type.FullName == fullName)
                    return type;

                var nested = FindTypeRecursive(type.NestedTypes, fullName);

                if (nested != null)
                    return nested;
            }

            return null;
        } 
    }
}
