using Microsoft.Build.Framework; 
using Mono.Cecil;
using Mono.Cecil.Cil;
using Mono.Cecil.Rocks;
using Mono.Collections.Generic;
using Myra.Xaml.Compiler;
using Myra.Xaml.Helpers;
using Myra.Xaml.Types;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using XamlX.Ast;
using XamlX.Parsers;
using XamlX.TypeSystem;

namespace Myra.Xaml
{ 
    /// <summary>
    /// Compiles .xaml files to IL and writes that to the target assembly.
    /// </summary>
    public sealed class MyraXamlCompileTask : Microsoft.Build.Utilities.Task
    { 

        [Required]
        public string TargetPath { get; set; } = default!;

        [Required]
        public ITaskItem[] XamlFiles { get; set; } = [];

        [Required]
        public string RootNamespace { get; set; } = null!;

        [Required]
        public string ProjectDirectory { get; set; } = null!;

        [Required]
        public ITaskItem[] ReferenceAssemblies { get; set; } = [];

        public bool Debug { get; set; }

        public CecilTypeSystem? TypeSystem { get; set; }

        private List<(string, IXamlMethod)> _stylesheetTypes = [];

        public override bool Execute()
        {
            Debugger.Launch();
            AssemblyDefinition? assembly = null;
            try
            {
                if (!File.Exists(TargetPath))
                {
                    Log.LogError("Myra XAML: target assembly '{0}' does not exist.", TargetPath);

                    return false;
                }

                if (XamlFiles.Length == 0)
                {
                    Log.LogMessage(MessageImportance.Low, "Myra XAML: no XAML files found.");

                    return true;
                }

                Log.LogMessage(MessageImportance.Normal, "Myra XAML: weaving '{0}'.", TargetPath);
                var assemblies = ReferenceAssemblies
                    .Select(x => x.ItemSpec)
                    .Where(File.Exists)
                    .Distinct(StringComparer.OrdinalIgnoreCase)
                    .ToList();
                TypeSystem = new CecilTypeSystem(assemblies, TargetPath);
                TypesContainer.Setup(TypeSystem);

                var componentsCompiler = new MyraComponentsCompiler(TypeSystem);
                var stylesheetsCompiler = new MyraStylesheetsCompiler(TypeSystem);

                assembly = componentsCompiler.TypeSystem.GetAssembly(componentsCompiler.TypeSystem.FindAssembly(Path.GetFileNameWithoutExtension(TargetPath)!)!);

                // write resource builder before we use it in the XAML handling.
                var resourceType = new TypeDefinition("Myra.AutoGenerated", "__MyraXamlResources", TypeAttributes.Class | TypeAttributes.Sealed,
                                                        assembly.MainModule.TypeSystem.Object);
                assembly.MainModule.Types.Add(resourceType);

                var writerParameters = new WriterParameters
                {
                    WriteSymbols = Debug,
                    SymbolWriterProvider = new PortablePdbWriterProvider()
                };
 
                assembly.Write(TargetPath, writerParameters);

                var resourcesBuilder = new MyraResourcesBuilder(TypeSystem, resourceType, stylesheetsCompiler.Configuration.WellKnownTypes);
                assembly.Write(TargetPath, writerParameters);
                var getMethod = resourceType.GetMethods().First(m => m.Name == "Get");
                MyraBindingCompilationContext.GetStylesheetDefinition = getMethod.Module.ImportReference(getMethod);


                // compile all XAML files
                foreach (var item in XamlFiles)
                {
                    CompileXamlFile(componentsCompiler, stylesheetsCompiler, assembly, item);
                } 

                // set up internal MyraResourcesClass for lookups. (for now, only stylesheets)  
                resourcesBuilder.BuildStaticConstructor(_stylesheetTypes);
                 
                assembly.Write(TargetPath, writerParameters);

                Log.LogMessage(MessageImportance.Normal, "Myra XAML: finished weaving '{0}'.", TargetPath);

                return !Log.HasLoggedErrors;
            }
            catch (Exception ex)
            {
                Log.LogErrorFromException(ex, showStackTrace: true);
                return false;
            }
            finally
            {
                assembly?.Dispose();
            }
        }

        private void CompileXamlFile(MyraComponentsCompiler componentsCompiler, 
                                     MyraStylesheetsCompiler stylesheetsCompiler,  
                                     AssemblyDefinition assembly,
                                     ITaskItem item)
        {
            var xamlPath = item.GetMetadata("FullPath");

            var xamlFileContents = File.ReadAllText(xamlPath);
            var document = XDocumentXamlParser.Parse(xamlFileContents); 

            if (string.IsNullOrWhiteSpace(xamlPath))
                xamlPath = item.ItemSpec;

            if (!Path.IsPathRooted(xamlPath))
                xamlPath = Path.GetFullPath(xamlPath);

            Log.LogMessage(MessageImportance.Normal, "Myra XAML: compiling '{0}'.",  xamlPath);

            if (!File.Exists(xamlPath))
            {
                Log.LogError("Myra XAML: XAML file '{0}' does not exist.", xamlPath);
                return;
            }

            var fileSource = new XamlFileSource(xamlPath, xamlFileContents);

            // check if it is a StyleSheet; if so, compile it as such.
            if (((XamlAstXmlTypeReference)((XamlAstObjectNode)document.Root).Type).Name == "Stylesheet")
            {
                var styleClassDefinition = new TypeDefinition("Myra.AutoGenerated", 
                    Path.GetFileNameWithoutExtension(fileSource.FilePath), TypeAttributes.Sealed,
                    assembly.MainModule.TypeSystem.Object);
                assembly.MainModule.Types.Add(styleClassDefinition);
                _stylesheetTypes.Add(stylesheetsCompiler.Compile(document, fileSource, styleClassDefinition)); 
                return;
            }

            // we now handle it as a custom component or page.
            var className = ClassHelper.GetClassType((document.Root as XamlAstObjectNode)!, item, xamlPath, ProjectDirectory);
            if (string.IsNullOrWhiteSpace(className))
            {
                Log.LogError("Myra XAML: could not determine the code-behind type for '{0}'. ", xamlPath);
                return;
            }

            var currentClassDefinition = FindTypeRecursive(assembly.MainModule.Types, className!);
            if (currentClassDefinition == null)
            {  
                // Note: the code-behind type must also be compiled before this MSBuild is invoked!
                Log.LogError("Myra XAML: code-behind type '{0}' was not found for XAML file '{1}'. ",
                    className,
                    TargetPath);

                return; 
            }

            var currentClass = TypeSystem!.FindType(currentClassDefinition.FullName);
            if (currentClass == null)
            { 
                throw new InvalidOperationException("This should never happen");
            }

            // ensure code-behind class derives from Widget.
            if (!TypesContainer.Widget.IsAssignableFrom(currentClass))
            {
                Log.LogError("Myra XAML: code-behind type '{0}' must derive from 'Myra.Graphics2D.UI.Widget'. ",
                  className,
                  TargetPath);
            }

            // ensure the Myra assembly is included
            var assemblyMappings = componentsCompiler.Configuration.XmlnsMappings.Namespaces[TransformerHelpers.MyraMappings];
            if (assemblyMappings.Any(a => a.ns != currentClass.Namespace && a.asm != currentClass.Assembly))
            {
                assemblyMappings.Add((currentClass.Assembly!, currentClass.Namespace!));
            } 

            Log.LogMessage(MessageImportance.Low, "Myra XAML: code-behind type is '{0}'.", currentClass.FullName);
             
            componentsCompiler.CompileInto(document, currentClassDefinition, fileSource);
        }  

        private static TypeDefinition? FindTypeRecursive(Collection<TypeDefinition> types, string fullName)
        {
            foreach (var type in types)
            {
                if (type.FullName == fullName)
                    return type;

                var nested = FindTypeRecursive(type.NestedTypes, fullName);

                if (nested != null)
                    return nested;
            }

            return null;
        } 
    }
}
