using Microsoft.Build.Framework;
using Mono.Cecil;
using Myra.Xaml.Helpers;
using Myra.Xaml.Transformers;
using Myra.Xaml.Types;
using System.Collections.Generic;
using System.IO;
using XamlX.Emit;
using XamlX.IL;
using XamlX.Parsers;
using XamlX.Transform;
using XamlX.Transform.Transformers;
using XamlX.TypeSystem;

namespace Myra.Xaml.Compiler
{
    /// <summary>
    /// Compiler for Stylesheets
    /// </summary>
    public sealed class MyraStylesheetsCompiler
    {
        public CecilTypeSystem TypeSystem { get; }
        public TransformerConfiguration Configuration { get; }

        private readonly XamlILCompiler _compiler;
        private static readonly Dictionary<string, string> _compabilityMappings
            = new Dictionary<string, string>()
            {
                { "", TransformerHelpers.MyraMappings }
            };

        public MyraStylesheetsCompiler(CecilTypeSystem typeSystem)
        {
            TypeSystem = typeSystem;
            Configuration = TransformerHelpers.CreateConfiguration(TypeSystem);
            var EmitMappings = new XamlLanguageEmitMappings<IXamlILEmitter, XamlILNodeEmitResult>();

            _compiler = new XamlILCompiler(Configuration, EmitMappings, false);
            _compiler.Transformers.AddRange(new IXamlAstTransformer[]
                {
                    new XamlIntrinsicsTransformer(),
                    new TextNodeMerger(),
                    new PropertyReferenceResolver(), 
                    new StylesheetReferenceResolver(),
                    new ContentConvertTransformer(),
                    // This should come before actual content property processing
                    new RemoveWhitespaceBetweenPropertyValuesTransformer(),
                    new NewObjectTransformer(),
                    new DeferredContentTransformer(),
                    new TopDownInitializationTransformer(),
                });
            _compiler.SimplificationTransformers.Add(new FlattenAstTransformer());
        }
        private const string initializeMethod = "initialize";
        private const string buildMethod = "Create";

        public (string, IXamlMethod) CompileStylesheetFile(AssemblyDefinition assembly, ITaskItem item)
        {
            var xamlPath = item.GetMetadata("FullPath");
            var xamlFileContents = File.ReadAllText(xamlPath);

            var fileSource = new XmlFileSource(xamlPath, xamlFileContents);
            var document = XDocumentXamlParser.Parse(xamlFileContents, _compabilityMappings);

            var styleClassDefinition = new TypeDefinition("Myra.AutoGenerated",
                Path.GetFileName(fileSource.FilePath).Replace('.', '_'), TypeAttributes.Sealed,
                assembly.MainModule.TypeSystem.Object);
            assembly.MainModule.Types.Add(styleClassDefinition);


            var typeBuilder = TypeSystem.CreateTypeBuilder(styleClassDefinition, false);
            // transform the document into an AST tree for compilation
            _compiler.Transform(document);

            // compile the AST into IL. The IL will be written to the DLL once all files have been compiled.
            var populate = _compiler.DefinePopulateMethod(typeBuilder, document, initializeMethod, XamlVisibility.Private);
            var build = _compiler.DefineBuildMethod(typeBuilder, document, "_create", XamlVisibility.Private);

            _compiler.Compile(
                document,
                _compiler.CreateContextType(typeBuilder),
                populate,
                typeBuilder,
                build,
                typeBuilder,
                null,
                Path.GetDirectoryName(fileSource.FilePath),
                fileSource);

            var createWrapper = typeBuilder.DefineMethod(TypesContainer.StyleSheet, [], buildMethod, XamlVisibility.Assembly, true, false);

            // Create() => _create(null);
            var wrapperCodeGen = createWrapper.Generator;
            wrapperCodeGen.Ldnull();
            wrapperCodeGen.EmitCall(build);
            wrapperCodeGen.Ret();

            typeBuilder.CreateType();
            return (Path.GetFileNameWithoutExtension(fileSource.FilePath), createWrapper);
        }
    }
}
