/* Generated by MyraPad at 04.12.2019 21:54:46 */
using Microsoft.Xna.Framework;
using Myra.Graphics2D.UI;

namespace Myra.Samples.NonModalWindows.UI 
{
	public partial class MainPanel : Panel
	{
        private ToggleButton Button1 { get; set; }
        private ToggleButton Button2 { get; set; } 
        private ToggleButton Button3 { get; set; } 
		public Label LabelOverGui { get; set; } 


        private readonly Window1 _window1 = new Window1();
		private readonly Window2 _window2 = new Window2();
		private readonly Window3 _window3 = new Window3();

		public MainPanel()
		{  
			_window1.Closed += (s, a) =>
			{
                Button1.IsPressed = false;
			};

			_window2.Closed += (s, a) =>
			{
                Button2.IsPressed = false;
			};

			_window3.Closed += (s, a) =>
			{
                Button3.IsPressed = false;
			};
		}

		public void ShowWindows()
		{
            Button1.IsPressed = true;
            Button2.IsPressed = true;
            Button3.IsPressed = true;
		}
		 
		private void _button1_PressedChanged(object sender, MyraEventArgs e)
		{
			if (Button1.IsPressed)
			{
				_window1.Show(Desktop, new Point(100, 100));
			}
			else
			{
				_window1.Close(); 
			}
		}

		private void _button2_PressedChanged(object sender, MyraEventArgs e)
		{
			if (Button2.IsPressed)
			{
				_window2.Show(Desktop, new Point(400, 100));
			} 
			else
			{
				_window2.Close();
			}
		}

		private void _button3_PressedChanged(object sender, MyraEventArgs e)
		{ 
			if (Button3.IsPressed)
			{
				_window3.Show(Desktop, new Point(200, 400));
			}
			else
			{
				_window3.Close();
			}
		}
	}
}