<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Myra.Samples.NonModalWindows</RootNamespace>
    <TargetFramework>$(AppTargetFramework)</TargetFramework>
    <OutputPath>bin\MonoGame\$(Configuration)</OutputPath>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="$(AppMonoGameVersion)" />
  </ItemGroup>

  <Import Project="$(MSBuildThisFileDirectory)..\samples.props" />
</Project>