/* Generated by Myra UI Editor at 10/2/2017 12:49:31 AM */

using Myra.Graphics2D.UI;

namespace Myra.Samples.Notepad
{
	public partial class Notepad : VerticalStackPanel
	{
		public HorizontalMenu _mainMenu { get; set; } = default!;
        public MenuItem menuItemFile { get; set; } = default!;
        public MenuItem menuItemNew { get; set; } = default!;
        public MenuItem menuItemOpen { get; set; } = default!;
        public MenuItem menuItemSave { get; set; } = default!;
        public MenuItem menuItemSaveAs { get; set; } = default!;
        public MenuItem menuItemDebugOptions { get; set; } = default!;
        public MenuItem menuItemQuit { get; set; } = default!;
        public MenuItem menuItemHelp { get; set; } = default!;
        public MenuItem menuItemAbout { get; set; } = default!;
        public TextBox textArea { get; set; } = default!;

    }
}