<Project> 
    <PropertyGroup>
	   <PublishAot>true</PublishAot>
	</PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Myra\Myra.MonoGame.csproj" />
  
	  <MyraXaml Include="**\*.xaml" />
	  <MyraXaml Include="..\..\src\Resources\*.xmms" LogicalPath="Resources\%(RecursiveDir)%(Filename)%(Extension)" />
 
	  <None Update="**\*.xaml">
		<MyraEditor>true</MyraEditor>
	  </None>
	  <Content Include="..\..\src\Resources\*.png" LinkBase="Resources">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="..\..\src\Resources\*.xmat" LinkBase="Resources">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content> 
	  <Content Include="..\..\src\Resources\*.ttf" LinkBase="Resources">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup> 
	
    <Target Name="MyraXamlRemoveStandardXamlItems"
          BeforeTargets="PrepareForBuild"> 
      <ItemGroup>
        <Page Remove="@(MyraXaml)" />
        <ApplicationDefinition Remove="@(MyraXaml)" />
      </ItemGroup> 
    </Target>
	
	<UsingTask TaskFactory="MyraXamlTaskFactory" TaskName="MyraXamlCompileTask" AssemblyFile="..\src\MyraXaml\bin\Debug\netstandard2.0\Myra.Xaml.dll" />

	<Target Name="MyraXamlCompile" AfterTargets="Build" Condition="'$(DesignTimeBuild)' != 'true'">  
	  <MyraXamlCompileTask TargetPath="$(TargetPath)"
						  MyraFiles="@(MyraXaml)" RootNamespace="$(RootNamespace)" ProjectDirectory="$(MSBuildProjectDirectory)" ReferenceAssemblies="@(ReferencePath)" Debug="$(DebugSymbols)" />
	  <MyraXamlCompileTask TargetPath="$(IntermediateOutputPath)$(TargetFileName)"
						   MyraFiles="@(MyraXaml)" RootNamespace="$(RootNamespace)" ProjectDirectory="$(MSBuildProjectDirectory)" ReferenceAssemblies="@(ReferencePath)" Debug="$(DebugSymbols)" />
	</Target> 
</Project>