<Project> 
    <ItemGroup>
      <ProjectReference Include="..\..\src\Myra\Myra.MonoGame.csproj" />
      <Content Include="..\..\src\Resources\*" LinkBase="Resources" />
 
	  <MyraXaml Include="**\*.xaml" /> 
	  <MyraXaml Include="..\..\src\Resources\**\*.xmms" LogicalPath="Resources\%(RecursiveDir)%(Filename)%(Extension)" />
	  <Content Update="..\..\src\Resources\*.png">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Update="..\..\src\Resources\*.xmat">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content> 
	  <Content Update="..\..\src\Resources\*.ttf">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup> 
	<UsingTask TaskFactory="MyraXamlTaskFactory" TaskName="MyraXamlCompileTask" AssemblyFile="..\src\MyraXaml\bin\Debug\netstandard2.0\Myra.Xaml.dll" />

	<Target Name="MyraXamlCompile" AfterTargets="Build" Condition="'$(DesignTimeBuild)' != 'true'">  
	  <MyraXamlCompileTask TargetPath="$(TargetPath)"
						  MyraFiles="@(MyraXaml)" RootNamespace="$(RootNamespace)" ProjectDirectory="$(MSBuildProjectDirectory)" ReferenceAssemblies="@(ReferencePath)" Debug="$(DebugSymbols)" />
	  <MyraXamlCompileTask TargetPath="$(IntermediateOutputPath)$(TargetFileName)"
						   MyraFiles="@(MyraXaml)" RootNamespace="$(RootNamespace)" ProjectDirectory="$(MSBuildProjectDirectory)" ReferenceAssemblies="@(ReferencePath)" Debug="$(DebugSymbols)" />
	</Target>
</Project>