<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(AppTargetFramework)</TargetFramework>
    <OutputPath>bin\MonoGame\$(Configuration)</OutputPath>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="$(AppMonoGameVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Myra\Myra.MonoGame.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="customers-10000.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None> 
  </ItemGroup>

  <ItemGroup>
    <MyraXaml Include="**\*.xaml" />
    <!-- Myra XAML analyzer -->
    <AdditionalFiles Include="@(MyraXaml)" />
    <Analyzer Include="..\..\src\MyraAnalyzer\bin\Debug\netstandard2.0\Myra.Analyzer.dll" />
  </ItemGroup>

  <UsingTask TaskFactory="MyraXamlTaskFactory" TaskName="MyraXamlCompileTask" AssemblyFile="..\..\src\MyraXaml\bin\Debug\netstandard2.0\Myra.Xaml.dll" />

  <Target Name="MyraXamlCompile" AfterTargets="Build" Condition="'$(DesignTimeBuild)' != 'true'">
    <MyraXamlCompileTask TargetPath="$(TargetPath)" XamlFiles="@(MyraXaml)" RootNamespace="$(RootNamespace)" ProjectDirectory="$(MSBuildProjectDirectory)" ReferenceAssemblies="@(ReferencePath)" Debug="$(DebugSymbols)" />
  </Target>
</Project>