<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Framework" Version="18.8.2" />
    <PackageReference Include="Microsoft.Build.Utilities.Core" Version="18.8.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup> 

  <ItemGroup>
    <ProjectReference Include="..\..\src\MyraXaml\MyraXaml.csproj" />
    <!-- Ensure CompilerTasks is build before MyraXaml -->
    <ProjectReference Include="..\CompilerTasks\CompilerTasks.csproj" SetConfiguration="Configuration=$(Configuration)" ReferenceOutputAssembly="true" PrivateAssets="all" />
  </ItemGroup>
 
</Project>
