/* Generated by MyraPad at 07.01.2020 0:18:36 */
using Myra.Graphics2D.UI;

namespace Myra.Samples.AssetManagement
{
	public partial class MainForm : Panel
	{
		public VerticalMenu _mainMenu { get; set; }
        public MenuItem _menuItemQuit { get; set; }

    }
}