<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DefineConstants>$(DefineConstants);MONOGAME</DefineConstants>
    <TargetFramework>net8</TargetFramework>
    <AssemblyName>Myra</AssemblyName>
    <PackageId>Myra</PackageId>
    <OutputPath>bin\MonoGame\$(Configuration)</OutputPath>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>


  <!-- Resources for NuGet package -->
  <ItemGroup Condition="'$(Configuration)'=='Release'">
    <None Include="..\MyraXaml\bin\$(Configuration)\netstandard2.0\*" Pack="true" PackagePath="build\Myra.Xaml\" />
    <None Include="..\MyraAnalyzer\bin\$(Configuration)\netstandard2.0\*" Pack="true" PackagePath="build\Myra.Analyzer\" />
    <None Include="Properties/Myra.props" Pack="true" PackagePath="build\" />
    <None Include="Properties/Myra.targets" Pack="true" PackagePath="build\" />
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  
  <!-- ensure MyraXaml and MyraAnalyzer are built before we pack them in -->
  <Target Name="BuildMyraXamlForPack" BeforeTargets="Pack" Condition="'$(Configuration)' == 'Release'">
    <MSBuild Projects="..\MyraXaml\MyraXaml.csproj" Targets="Build" Properties="Configuration=Release" />
    <MSBuild Projects="..\MyraAnalyzer\MyraAnalyzer.csproj" Targets="Build" Properties="Configuration=Release" />
  </Target>

  <ItemGroup>
    <Compile Remove="Platform\**\*.*" />
    <Compile Remove="Resources\**" />
    <EmbeddedResource Remove="Resources\**" />
    <None Remove="Resources\**" />
    <Compile Update="Graphics2D\UI\File\FileDialog.PlatformDependent.cs">
      <DependentUpon>FileDialog.cs</DependentUpon>
    </Compile>
    <Compile Update="Graphics2D\UI\File\FileDialog.Util.cs">
      <DependentUpon>FileDialog.cs</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="XNAssets.MonoGame" Version="$(XNAssetsVersion)" />
    <PackageReference Include="XNAssets.FontStashSharp.MonoGame" Version="$(XNAssetsVersion)" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" PrivateAssets="All" Version="$(MonoGameVersion)" />
  </ItemGroup>
</Project>